apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-app-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: js-app
  template:
    metadata:
      labels:
        app: js-app
    spec:
      containers:
      - name: js-app
        image: raghu6289/auth-mernstack:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: js-app-service
  namespace: default
spec:
  selector:
    app: js-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
